from ..parser import parse_from_cli as parse_from_cli
from .args import SlurmArgs as SlurmArgs
from .task import PyTorchDistributedTask as PyTorchDistributedTask
from typing import Any, Callable

def get_slurm_executor(slurm_config: SlurmArgs, slurm_parameters_kwargs: dict = {}, slurm_submission_kwargs: dict = {}): ...
def slurm_has_been_set_up() -> bool: ...
def slurm_launcher(ArgsType: type[Any], parser: str | Callable = 'tyro', slurm_key: str = 'slurm', slurm_params_kwargs: dict = {}, slurm_submit_kwargs: dict = {}, slurm_task_kwargs: dict = {}, *extra_args, **extra_kwargs): ...
def slurm_distributed_launcher(ArgsType: type[Any], parser: str | Callable = 'tyro', slurm_key: str = 'slurm', slurm_params_kwargs: dict = {}, slurm_submit_kwargs: dict = {}, slurm_task_kwargs: dict = {}, *extra_args, **extra_kwargs): ...
def slurm_function(submit_fn: Callable): ...
