site_name: NNTool

nav:
  - Home: index.md
  - Examples:
    - Distributed Training with Hugging Face Accelerate: examples/distributed_training.md
  - Documentation:
    - nntool.slurm:
      - slurm_fn: documentation/slurm.md
      - SlurmFunction: documentation/slurm_function.md
    - nntool.experiment: documentation/experiment.md
    - nntool.wandb: documentation/wandb.md
    - nntool.utils: documentation/utils.md

theme:
  name: 'material'
  favicon: asset/logo-black.png
  logo: asset/logo-black.png
  # icon:
    # logo: simple/runkit
  palette:
    - primary: white
    - accent: indigo
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - navigation.footer
  # Palette toggle for automatic mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_section_style: table
            show_root_heading: false
            parameter_headings: true
            show_source: false
            heading_level: 3
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: "&copy; Copyright 2024, Junhao Liu."

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jhliu17
    - icon: fontawesome/solid/paper-plane
      link: mailto:junhaoliu17@gmail.com