site_name: NNTool

nav:
  - Home: index.md
  - Documentation:
    - nntool.slurm:
      - Configuration: documentation/slurm.md
      - SlurmFunction: documentation/slurm_function.md
    - nntool.wandb: documentation/wandb.md
    - nntool.utils: documentation/utils.md

theme:
  name: 'material'
  icon:
    logo: simple/runkit
  palette:
    - primary: white
    - accent: indigo
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
  # Palette toggle for automatic mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_section_style: table
            show_root_heading: false
            parameter_headings: true
            show_source: false
            heading_level: 3
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences