site_name: NNTool

nav:
  - Home: index.md
  - Documentation:
    - nntool.slurm:
      - Configuration: documentation/slurm.md
      - SlurmFunction: documentation/slurm_function.md
    - nntool.wandb: documentation/wandb.md

theme:
  name: 'material'
  icon:
    logo: material/floor-lamp-torchiere-variant
  palette:
    primary: white
    accent: blue gray
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_section_style: table
            show_root_heading: false
            parameter_headings: true
            show_source: false
            heading_level: 3
            show_signature_annotations: true
            separate_signature: true
